site_name: Canonical Kubernetes CAPI
site_description: Documentation site for the Canonical Kubernetes CAPI training

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy

extra_css:
  - stylesheets/extra.css

nav:
  - "📄 Home": index.md
  - "📋 Kubernetes Basics": 1-kubernetes-basics.md
  - "📋 Networking": 2-networking.md
  - "📋 Keeping apps healthy": 3-keeping-apps-healthy.md
  - "📋 Storage and User Data": 4-storage-and-user-data.md
  - "📋 Autoscaling": 5-autoscaling.md
  - "📋 AuthN and AuthZ": 6-authentication-and-authorization.md
  - "📋 Helm": 7-helm.md
  - "⏳ Upgrades": 8-upgrading-canonical-kubernetes.md

markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
      title: On this page
  - attr_list
  - md_in_html

plugins:
  - search
