apiVersion: v2
name: canonical-kubernetes-capi
version: 0.0.23
description: A Helm chart for MkDocs support for Canonical Kubernetes CAPI training
appVersion: 0.0.23
dependencies:
  - name: redis
    version: "18.1.2"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
